# Stage 1: Build the React application
FROM node:20-alpine as build-stage

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:stable-alpine as production-stage

# Copiar el build del frontend
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copiar el default.conf al contenedor NGINX
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]